### ISSUE TITLE
Bug in DestinationModel training_score method

### ISSUE THREAD

**Issue by phipag** [phipag/PDS_Project#7] opened 2020-05-31 10:15 UTC
Dear team,

when using the training_score method on the destination model I am experiencing the following error:
```
Traceback (most recent call last):
  File "/Users/phipag/Git/pds/PDS_Project/venv/bin/nextbike", line 11, in <module>
    load_entry_point('PDS-Project==0.0.1.dev1', 'console_scripts', 'nextbike')()
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/nextbike/cli/train/commands.py", line 28, in train
    destination_model.training_score()
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/nextbike/models/DestinationModel.py", line 140, in training_score
    pred_transformed = self.encoder.inverse_transform(self.predictions)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/preprocessing/_label.py", line 289, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/Users/phipag/Git/pds/PDS_Project/venv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 797, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape ()
```

This is the code I am using:
```python
destination_model = DestinationModel()
destination_model.load_from_csv(filename)
destination_model.train()
destination_model.training_score()
```

**Comment by LHumpe** [comment] 2020-05-31 10:19
Duplicate of #6 

This is not a bug same as the duplicate above :)

**Closed as completed by LHumpe** 2020-05-31 10:19 UTC
Labels: bug
